/**
 * This file is auto-generated by openapi-typescript.
 * Run `pnpm generate:api` (with the backend running) to regenerate.
 */

export interface paths {
  '/api/plates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          search?: string
          manufacturerId?: string
          wellCount?: number
          pageIndex?: number
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: {
            'application/json': components['schemas']['PagedResultOfPlateResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/plates/{id}': {
    parameters: {
      query?: never
      header?: never
      path: { id: string }
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: { id: string }
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: {
            'application/json': components['schemas']['PlateDetailResponse']
          }
        }
        404: { headers: Record<string, unknown>; content?: never }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/{id}/download': {
    parameters: {
      query?: never
      header?: never
      path: { id: string }
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: { id: string }
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: { 'application/octet-stream': Blob }
        }
        404: { headers: Record<string, unknown>; content?: never }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/manufacturers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: {
            'application/json': components['schemas']['ManufacturerResponse'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/manufacturers/{id}': {
    parameters: {
      query?: never
      header?: never
      path: { id: string }
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: { id: string }
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: {
            'application/json': components['schemas']['ManufacturerDetailResponse']
          }
        }
        404: { headers: Record<string, unknown>; content?: never }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/materials': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: {
            'application/json': components['schemas']['MaterialResponse'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/plates/{plateId}/files': {
    parameters: {
      query?: never
      header?: never
      path: { plateId: string }
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: { plateId: string }
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: Record<string, unknown>
          content: {
            'application/json': components['schemas']['PlateFileResponse'][]
          }
        }
        404: { headers: Record<string, unknown>; content?: never }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}

export interface components {
  schemas: {
    MaterialSummary: {
      code: string
      name: string
    }
    PlatePropertyResponse: {
      name: string
      value: string
    }
    PlateResponse: {
      id: string
      name: string
      catalogNumber: string
      wellCount: number
      material: components['schemas']['MaterialSummary']
      manufacturerId: string
      manufacturerName: string
      properties: components['schemas']['PlatePropertyResponse'][]
    }
    PagedResultOfPlateResponse: {
      items: components['schemas']['PlateResponse'][]
      totalCount: number
      pageIndex: number
      pageSize: number
    }
    FileResponse: {
      id: string
      fileName: string
      contentType: string
    }
    PlateDetailResponse: {
      id: string
      name: string
      catalogNumber: string
      wellCount: number
      material: components['schemas']['MaterialSummary']
      manufacturerId: string
      manufacturerName: string
      properties: components['schemas']['PlatePropertyResponse'][]
      files: components['schemas']['FileResponse'][]
    }
    ManufacturerResponse: {
      id: string
      name: string
    }
    ManufacturerDetailResponse: {
      id: string
      name: string
    }
    MaterialResponse: {
      id: string
      code: string
      name: string
      description: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type webhooks = Record<string, never>
