/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatesIndexRouteImport } from './routes/plates.index'
import { Route as ManufacturersIndexRouteImport } from './routes/manufacturers.index'
import { Route as PlatesIdRouteImport } from './routes/plates.$id'
import { Route as ManufacturersIdRouteImport } from './routes/manufacturers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatesIndexRoute = PlatesIndexRouteImport.update({
  id: '/plates/',
  path: '/plates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersIndexRoute = ManufacturersIndexRouteImport.update({
  id: '/manufacturers/',
  path: '/manufacturers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatesIdRoute = PlatesIdRouteImport.update({
  id: '/plates/$id',
  path: '/plates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersIdRoute = ManufacturersIdRouteImport.update({
  id: '/manufacturers/$id',
  path: '/manufacturers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manufacturers/$id': typeof ManufacturersIdRoute
  '/plates/$id': typeof PlatesIdRoute
  '/manufacturers': typeof ManufacturersIndexRoute
  '/plates': typeof PlatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manufacturers/$id': typeof ManufacturersIdRoute
  '/plates/$id': typeof PlatesIdRoute
  '/manufacturers': typeof ManufacturersIndexRoute
  '/plates': typeof PlatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manufacturers/$id': typeof ManufacturersIdRoute
  '/plates/$id': typeof PlatesIdRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/plates/': typeof PlatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manufacturers/$id'
    | '/plates/$id'
    | '/manufacturers'
    | '/plates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manufacturers/$id' | '/plates/$id' | '/manufacturers' | '/plates'
  id:
    | '__root__'
    | '/'
    | '/manufacturers/$id'
    | '/plates/$id'
    | '/manufacturers/'
    | '/plates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManufacturersIdRoute: typeof ManufacturersIdRoute
  PlatesIdRoute: typeof PlatesIdRoute
  ManufacturersIndexRoute: typeof ManufacturersIndexRoute
  PlatesIndexRoute: typeof PlatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plates/': {
      id: '/plates/'
      path: '/plates'
      fullPath: '/plates'
      preLoaderRoute: typeof PlatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers/': {
      id: '/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plates/$id': {
      id: '/plates/$id'
      path: '/plates/$id'
      fullPath: '/plates/$id'
      preLoaderRoute: typeof PlatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers/$id': {
      id: '/manufacturers/$id'
      path: '/manufacturers/$id'
      fullPath: '/manufacturers/$id'
      preLoaderRoute: typeof ManufacturersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManufacturersIdRoute: ManufacturersIdRoute,
  PlatesIdRoute: PlatesIdRoute,
  ManufacturersIndexRoute: ManufacturersIndexRoute,
  PlatesIndexRoute: PlatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
